In [1]:
import pandas as pd

In [ ]:
population = pd.read_csv('고령자현황.csv')
population.head()

,동별(1),동별(2),2022,2022.1,2022.2,2022.3,2022.4,2022.5,2022.6,2022.7,2022.8
0,동별(1),동별(2),65세이상 인구,65세이상 인구,65세이상 인구,65세이상 인구,65세이상 인구,65세이상 인구,65세이상 인구,65세이상 인구,65세이상 인구
1,동별(1),동별(2),소계,남자,여자,내국인,내국인,내국인,외국인,외국인,외국인
2,동별(1),동별(2),소계,소계,소계,소계,남자,여자,소계,남자,여자
3,합계,소계,1667411,739300,928111,1658207,734417,923790,9204,4883,4321
4,합계,종로구,27958,12592,15366,27704,12448,15256,254,144,110

In [ ]:
population.drop([0,1,2,3], axis=0, inplace=True)

In [ ]:
population = population[['동별(2)','2022.3']]
population.rename(columns={'동별(2)':'자치구','2022.3':'노인인구수'}, inplace=True)
population.head()

   자치구  노인인구수
4  종로구  27704
5   중구  24660
6  용산구  38478
7  성동구  47530
8  광진구  53737

In [ ]:
subway = pd.read_csv('서울교통공사_자치구별지하철역정보_20230531.CSV', encoding='cp949')
subway.drop(['해당역(호선)'], axis=1, inplace=True)
subway.head()

   자치구  역개수
0  강남구   21
1  강동구   14
2  강북구    3
3  강서구    9
4  관악구    4

In [ ]:
free = pd.read_csv('전국무료급식소표준데이터.csv', encoding= 'cp949')
free = pd.DataFrame(free['제공기관명'])
free=free.loc[free['제공기관명'].str.contains("서울"),:]
free = pd.DataFrame([['강서구',14],['성북구',11],['중랑구',11],['강북구',11],['마포구',11],['강남구',11],['은평구',10],['양천구',10],
                     ['동작구',9],['서대문구',8],['금천구',7],['구로구',6],['관악구',6],['종로구',5],['영등포구',5],['서초구',5],
                     ['성동구',5],['강동구',4],['노원구',3],['용산구',3],['광진구',2],['동대문구',2],['중구',2],['송파구',1],['도봉구',0
                     ]])
free=free.rename(columns={0:'자치구',1:'무료급식소개수'})
free.head()

   자치구  무료급식소개수
0  강서구       14
1  성북구       11
2  중랑구       11
3  강북구       11
4  마포구       11

In [ ]:
income = pd.read_csv('서울시_소득정보.csv')
income = income[income['adstrd_nm'].str.contains("서울특별시")]
income = income.loc[:,['adstrd_nm','ave_income_amt']]
income = income.rename(columns={'adstrd_nm':'자치구','ave_income_amt':'평균소득'})
income.reset_index(drop=True, inplace=True)

In [ ]:
jcg = pd.DataFrame([['강서구',0],['성북구',0],['중랑구',0],['강북구',0],['마포구',0],['강남구',0],['은평구',0],['양천구',0],
                     ['동작구',0],['서대문구',0],['금천구',0],['구로구',0],['관악구',0],['종로구',0],['영등포구',0],['서초구',0],
                     ['성동구',0],['강동구',0],['노원구',0],['용산구',0],['광진구',0],['동대문구',0],['중구',0],['송파구',0],['도봉구',0
                     ]])
jcg=jcg.rename(columns={0:'자치구',1:'평균소득'})

In [ ]:
for i in range(len(income)):
    if '강서구' in income.loc[i,'자치구']:
        jcg.loc[0,'평균소득'] += income.loc[i,'평균소득']
    elif '성북구' in income.loc[i,'자치구']:
        jcg.loc[1,'평균소득'] += income.loc[i,'평균소득']
    elif '중랑구' in income.loc[i,'자치구']:
        jcg.loc[2,'평균소득'] += income.loc[i,'평균소득']
    elif '강북구' in income.loc[i,'자치구']:
        jcg.loc[3,'평균소득'] += income.loc[i,'평균소득']
    elif '마포구' in income.loc[i,'자치구']:
        jcg.loc[4,'평균소득'] += income.loc[i,'평균소득']
    elif '강남구' in income.loc[i,'자치구']:
        jcg.loc[5,'평균소득'] += income.loc[i,'평균소득']
    elif '은평구' in income.loc[i,'자치구']:
        jcg.loc[6,'평균소득'] += income.loc[i,'평균소득']
    elif '양천구' in income.loc[i,'자치구']:
        jcg.loc[7,'평균소득'] += income.loc[i,'평균소득']
    elif '동작구' in income.loc[i,'자치구']:
        jcg.loc[8,'평균소득'] += income.loc[i,'평균소득']
    elif '서대문구' in income.loc[i,'자치구']:
        jcg.loc[9,'평균소득'] += income.loc[i,'평균소득']
    elif '금천구' in income.loc[i,'자치구']:
        jcg.loc[10,'평균소득'] += income.loc[i,'평균소득']
    elif '구로구' in income.loc[i,'자치구']:
        jcg.loc[11,'평균소득'] += income.loc[i,'평균소득']
    elif '관악구' in income.loc[i,'자치구']:
        jcg.loc[12,'평균소득'] += income.loc[i,'평균소득']
    elif '종로구' in income.loc[i,'자치구']:
        jcg.loc[13,'평균소득'] += income.loc[i,'평균소득']
    elif '영등포구' in income.loc[i,'자치구']:
        jcg.loc[14,'평균소득'] += income.loc[i,'평균소득']
    elif '서초구' in income.loc[i,'자치구']:
        jcg.loc[15,'평균소득'] += income.loc[i,'평균소득']
    elif '성동구' in income.loc[i,'자치구']:
        jcg.loc[16,'평균소득'] += income.loc[i,'평균소득']
    elif '강동구' in income.loc[i,'자치구']:
        jcg.loc[17,'평균소득'] += income.loc[i,'평균소득']
    elif '노원구' in income.loc[i,'자치구']:
        jcg.loc[18,'평균소득'] += income.loc[i,'평균소득']
    elif '용산구' in income.loc[i,'자치구']:
        jcg.loc[19,'평균소득'] += income.loc[i,'평균소득']
    elif '광진구' in income.loc[i,'자치구']:
        jcg.loc[20,'평균소득'] += income.loc[i,'평균소득']
    elif '동대문구' in income.loc[i,'자치구']:
        jcg.loc[21,'평균소득'] += income.loc[i,'평균소득']
    elif '중구' in income.loc[i,'자치구']:
        jcg.loc[22,'평균소득'] += income.loc[i,'평균소득']
    elif '송파구' in income.loc[i,'자치구']:
        jcg.loc[23,'평균소득'] += income.loc[i,'평균소득']
    elif '도봉구' in income.loc[i,'자치구']:
        jcg.loc[24,'평균소득'] += income.loc[i,'평균소득']

C:\Users\hi\AppData\Local\Temp\ipykernel_10920\610921274.py:29: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '9049.02' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  jcg.loc[13,'평균소득'] += income.loc[i,'평균소득']

In [ ]:
jcg = jcg.sort_values('평균소득',ascending=False)
jcg.reset_index(drop=True,inplace=True)
jcg

     자치구       평균소득
0     중구  514885.03
1    종로구  511560.78
2    강남구  381329.56
3    서초구  241373.27
4    마포구  221496.77
5    용산구  205362.88
6    송파구  204761.09
7    성북구  201460.52
8   영등포구  183920.64
9    강서구  165836.25
10   강동구  115077.66
11  서대문구  113342.16
12   성동구  108831.40
13   관악구  106253.56
14   동작구   96179.79
15   광진구   84653.23
16   양천구   81703.18
17   노원구   72355.74
18   구로구   71923.18
19   은평구   68081.73
20   중랑구   61681.28
21  동대문구   56262.18
22   도봉구   52194.37
23   강북구   50225.22
24   금천구   42087.28

In [ ]:
jcg.iloc[0,1] = jcg.iloc[0,1] / 86
jcg.iloc[1,1] = jcg.iloc[1,1] / 93
jcg.iloc[2,1] = jcg.iloc[2,1] / 31
jcg.iloc[3,1] = jcg.iloc[3,1] / 23
jcg.iloc[4,1] = jcg.iloc[4,1] / 41
jcg.iloc[5,1] = jcg.iloc[5,1] / 37
jcg.iloc[6,1] = jcg.iloc[6,1] / 28
jcg.iloc[7,1] = jcg.iloc[7,1] / 51
jcg.iloc[8,1] = jcg.iloc[8,1] / 43
jcg.iloc[9,1] = jcg.iloc[9,1] / 33
jcg.iloc[10,1] = jcg.iloc[10,1] / 19
jcg.iloc[11,1] = jcg.iloc[11,1] / 26
jcg.iloc[12,1] = jcg.iloc[12,1] / 23
jcg.iloc[13,1] = jcg.iloc[13,1] / 21
jcg.iloc[14,1] = jcg.iloc[14,1] / 18
jcg.iloc[15,1] = jcg.iloc[15,1] / 15
jcg.iloc[16,1] = jcg.iloc[16,1] / 18
jcg.iloc[17,1] = jcg.iloc[17,1] / 19
jcg.iloc[18,1] = jcg.iloc[18,1] / 18
jcg.iloc[19,1] = jcg.iloc[19,1] / 16
jcg.iloc[20,1] = jcg.iloc[20,1] / 16
jcg.iloc[21,1] = jcg.iloc[21,1] / 15
jcg.iloc[22,1] = jcg.iloc[22,1] / 14
jcg.iloc[23,1] = jcg.iloc[23,1] / 14
jcg.iloc[24,1] = jcg.iloc[24,1] / 10

In [ ]:
jcg = jcg.sort_values('평균소득',ascending=False)
jcg.reset_index(drop=True,inplace=True)
jcg

     자치구          평균소득
0    강남구  12300.953548
1    서초구  10494.490000
2    송파구   7312.896071
3    강동구   6056.718947
4     중구   5987.035233
5    광진구   5643.548667
6    용산구   5550.348108
7    종로구   5500.653548
8    마포구   5402.360244
9    동작구   5343.321667
10   관악구   5059.693333
11   강서구   5025.340909
12   성동구   4731.800000
13   양천구   4539.065556
14  서대문구   4359.313846
15  영등포구   4277.224186
16   은평구   4255.108125
17   금천구   4208.728000
18   구로구   3995.732222
19   성북구   3950.206275
20   중랑구   3855.080000
21   노원구   3808.196842
22  동대문구   3750.812000
23   도봉구   3728.169286
24   강북구   3587.515714

In [ ]:
jcg_midx = jcg.drop(12,axis=0)
jcg_midx = jcg.drop('자치구',axis=1)
jcg_midx_jal = jcg_midx[0:7]
jcg_midx_mid = jcg_midx[8:16]
jcg_midx_mot = jcg_midx[17:24]

In [ ]:
from scipy import stats
F_statistic, pVal = stats.f_oneway(jcg_midx_jal, jcg_midx_mid, jcg_midx_mot)
print("F통계량: ",F_statistic,"유의확률:", pVal)
#print('데이터의 일원분산분석 결과 : F={0:.1f}, p={1:.10f}'.format(F_statistic, pVal))
#print('데이터의 일원분산분석 결과 : F=%.2f , p=%.10f ' %(F_statistic, pVal))

F통계량:  [11.12787458] 유의확률: [0.00063249]

In [ ]:
sowe1 = pd.read_csv('서울시 사회복지시설(노인주거복지시설) 목록.csv', encoding= 'cp949')
sowe2 = pd.read_csv('서울시 사회복지시설(재가노인복지시설) 목록.csv', encoding= 'cp949')
sowe1 = pd.DataFrame(sowe1.loc[:,'시군구명'])
sowe2 = pd.DataFrame(sowe2.loc[:,'시군구명'])
idx = sowe1[sowe1['시군구명'] == "서울특별시"].index
sowe1.drop(idx , inplace=True)
idx = sowe2[sowe2['시군구명'] == "서울특별시"].index
sowe2.drop(idx , inplace=True)
sowe1.reset_index(drop=True, inplace=True)
sowe2.reset_index(drop=True, inplace=True)

In [ ]:
sowe1.value_counts()

시군구명
강서구     3
강남구     2
광진구     2
금천구     2
노원구     2
도봉구     2
은평구     2
중구      2
강동구     1
마포구     1
성북구     1
양천구     1
영등포구    1
용산구     1
종로구     1
Name: count, dtype: int64

In [ ]:
sowe_list = pd.DataFrame([['강서구',0],['성북구',0],['중랑구',0],['강북구',0],['마포구',0],['강남구',0],['은평구',0],['양천구',0],
                     ['동작구',0],['서대문구',0],['금천구',0],['구로구',0],['관악구',0],['종로구',0],['영등포구',0],['서초구',0],
                     ['성동구',0],['강동구',0],['노원구',0],['용산구',0],['광진구',0],['동대문구',0],['중구',0],['송파구',0],['도봉구',0
                     ]])
sowe_list=sowe_list.rename(columns={0:'자치구',1:'시설개수'})

In [ ]:
for i in range(len(sowe1)):
    if (sowe1.loc[i,'시군구명'] == '강서구'):
        sowe_list.loc[0,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '성북구'):
        sowe_list.loc[1,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '중랑구'):
        sowe_list.loc[2,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '강북구'):
        sowe_list.loc[3,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '마포구'):
        sowe_list.loc[4,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '강남구'):
        sowe_list.loc[5,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '은평구'):
        sowe_list.loc[6,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '양천구'):
        sowe_list.loc[7,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '동작구'):
        sowe_list.loc[8,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '서대문구'):
        sowe_list.loc[9,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '금천구'):
        sowe_list.loc[10,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '구로구'):
        sowe_list.loc[11,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '관악구'):
        sowe_list.loc[12,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '종로구'):
        sowe_list.loc[13,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '영등포구'):
        sowe_list.loc[14,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '서초구'):
        sowe_list.loc[15,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '성동구'):
        sowe_list.loc[16,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '강동구'):
        sowe_list.loc[17,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '노원구'):
        sowe_list.loc[18,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '용산구'):
        sowe_list.loc[19,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '광진구'):
        sowe_list.loc[20,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '동대문구'):
        sowe_list.loc[21,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '중구'):
        sowe_list.loc[22,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '송파구'):
        sowe_list.loc[23,'시설개수'] += 1
    elif (sowe1.loc[i,'시군구명'] == '도봉구'):
        sowe_list.loc[24,'시설개수'] += 1

In [ ]:
for i in range(len(sowe2)):
    if (sowe2.loc[i,'시군구명'] == '강서구'):
        sowe_list.loc[0,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '성북구'):
        sowe_list.loc[1,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '중랑구'):
        sowe_list.loc[2,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '강북구'):
        sowe_list.loc[3,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '마포구'):
        sowe_list.loc[4,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '강남구'):
        sowe_list.loc[5,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '은평구'):
        sowe_list.loc[6,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '양천구'):
        sowe_list.loc[7,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '동작구'):
        sowe_list.loc[8,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '서대문구'):
        sowe_list.loc[9,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '금천구'):
        sowe_list.loc[10,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '구로구'):
        sowe_list.loc[11,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '관악구'):
        sowe_list.loc[12,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '종로구'):
        sowe_list.loc[13,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '영등포구'):
        sowe_list.loc[14,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '서초구'):
        sowe_list.loc[15,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '성동구'):
        sowe_list.loc[16,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '강동구'):
        sowe_list.loc[17,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '노원구'):
        sowe_list.loc[18,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '용산구'):
        sowe_list.loc[19,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '광진구'):
        sowe_list.loc[20,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '동대문구'):
        sowe_list.loc[21,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '중구'):
        sowe_list.loc[22,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '송파구'):
        sowe_list.loc[23,'시설개수'] += 1
    elif (sowe2.loc[i,'시군구명'] == '도봉구'):
        sowe_list.loc[24,'시설개수'] += 1

In [ ]:
sowe_list

     자치구  시설개수
0    강서구    40
1    성북구    28
2    중랑구    48
3    강북구    35
4    마포구    29
5    강남구    24
6    은평구    41
7    양천구    35
8    동작구    29
9   서대문구    23
10   금천구    18
11   구로구    25
12   관악구    29
13   종로구     8
14  영등포구    22
15   서초구    12
16   성동구    19
17   강동구    31
18   노원구    46
19   용산구     7
20   광진구    22
21  동대문구    35
22    중구    11
23   송파구    41
24   도봉구    29

In [ ]:
data=pd.merge(population,subway, on="자치구")
data=pd.merge(data,free, on="자치구")
data=pd.merge(data,sowe_list, on="자치구")
data

     자치구   노인인구수  역개수  무료급식소개수  시설개수
0    종로구   27704   15        5     8
1     중구   24660   23        2    11
2    용산구   38478   10        3     7
3    성동구   47530   14        5    19
4    광진구   53737   11        2    22
5   동대문구   64255    6        2    35
6    중랑구   74790    8       11    48
7    성북구   77293    9       11    28
8    강북구   66170    3       11    35
9    도봉구   66942    3        0    29
10   노원구   91946   13        3    46
11   은평구   89422   13       10    41
12  서대문구   55502    5        8    23
13   마포구   55533   16       11    29
14   양천구   72235    5       10    35
15   강서구   96880    9       14    40
16   구로구   74491    7        6    25
17   금천구   42226    1        7    18
18  영등포구   63349   11        5    22
19   동작구   67872   12        9    29
20   관악구   81848    4        6    29
21   서초구   62228   12        5    12
22   강남구   81564   21       11    24
23   송파구  103361   28        1    41
24   강동구   78191   14        4    31

In [42]:
data.to_csv('final_clusters.csv')

NameError: ignored

In [ ]:
#######################################################3

In [2]:
import pandas as pd

In [3]:
cluster = pd.read_csv('/content/final_clusters.csv',encoding='cp949')
cluster.head()

   Unnamed: 0  자치구  노인인구수  역개수  무료급식소개수  시설개수
0           0  종로구  27704   15        5     8
1           1   중구  24660   23        2    11
2           2  용산구  38478   10        3     7
3           3  성동구  47530   14        5    19
4           4  광진구  53737   11        2    22

In [19]:
addition = pd.read_csv('/content/부양비+및+노령화지수.csv')
addition.head()

   동별(1)  동별(2)   2022 2022.1 2022.2
0  동별(1)  동별(2)  유년부양비  노년부양비  노령화지수
1    서울시     소계   13.0   23.6  180.7
2    종로구     소계   10.4   24.8  238.5
3    종로구    사직동   13.0   27.1  208.3
4    종로구    삼청동   13.2   35.1  266.4

In [20]:
addition.dtypes

동별(1)     object
동별(2)     object
2022      object
2022.1    object
2022.2    object
dtype: object

In [21]:
addition.drop([0,1], axis=0, inplace=True)
addition

    동별(1) 동별(2)  2022 2022.1 2022.2
2     종로구    소계  10.4   24.8  238.5
3     종로구   사직동  13.0   27.1  208.3
4     종로구   삼청동  13.2   35.1  266.4
5     종로구   부암동  11.6   26.2  225.6
6     종로구   평창동  14.4   27.8  192.8
..    ...   ...   ...    ...    ...
448   강동구  암사1동  12.1   25.3  208.4
449   강동구  천호2동   9.7   24.3  250.6
450   강동구    길동  10.3   25.4  245.5
451   강동구  상일1동  27.5   18.0   65.3
452   강동구  상일2동  22.3   23.3  104.9

[451 rows x 5 columns]

In [7]:
  #2022 - 유년부양비, 2022.1 - 노년부양비, 2022.2 - 노령화지수

In [22]:
addition[['2022','2022.1','2022.2']] = addition[['2022','2022.1','2022.2']].apply(pd.to_numeric)

In [34]:
addition.dtypes

동별(1)     object
동별(2)     object
유년부양비    float64
노년부양비    float64
노령화지수    float64
dtype: object

In [35]:
addmean = addition.groupby('동별(1)').mean()
addmean

<ipython-input-35-26b1e1583d5d>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  addmean = addition.groupby('동별(1)').mean()

           유년부양비      노년부양비       노령화지수
동별(1)
강남구    15.717391  23.226087  173.782609
강동구    15.965000  23.200000  174.215000
강북구    10.428571  32.571429  336.078571
강서구    12.466667  25.090476  229.895238
관악구     8.163636  21.795455  293.304545
광진구    10.368750  20.468750  226.293750
구로구    13.405882  24.905882  219.117647
금천구    10.090909  25.509091  260.200000
노원구    13.955000  25.335000  195.720000
도봉구    12.000000  30.720000  265.320000
동대문구   11.233333  25.086667  239.086667
동작구    11.656250  24.018750  231.975000
마포구    12.400000  19.658824  178.841176
서대문구   13.480000  24.480000  198.193333
서초구    18.257895  21.578947  125.952632
성동구    12.338889  22.394444  199.255556
성북구    13.033333  24.128571  211.595238
송파구    15.203571  22.721429  175.582143
양천구    15.715789  23.315789  168.878947
영등포구   12.436842  22.589474  196.747368
용산구    11.364706  23.217647  234.970588
은평구    12.423529  26.835294  237.970588
종로구    10.444444  26.044444  290.805556
중구      9.512500  25.875000  308.550000
중랑구    11.447059  26.635294  247.900000

In [25]:
print(addition.groupby('동별(1)').mean())

            2022     2022.1      2022.2
동별(1)
강남구    15.717391  23.226087  173.782609
강동구    15.965000  23.200000  174.215000
강북구    10.428571  32.571429  336.078571
강서구    12.466667  25.090476  229.895238
관악구     8.163636  21.795455  293.304545
광진구    10.368750  20.468750  226.293750
구로구    13.405882  24.905882  219.117647
금천구    10.090909  25.509091  260.200000
노원구    13.955000  25.335000  195.720000
도봉구    12.000000  30.720000  265.320000
동대문구   11.233333  25.086667  239.086667
동작구    11.656250  24.018750  231.975000
마포구    12.400000  19.658824  178.841176
서대문구   13.480000  24.480000  198.193333
서초구    18.257895  21.578947  125.952632
성동구    12.338889  22.394444  199.255556
성북구    13.033333  24.128571  211.595238
송파구    15.203571  22.721429  175.582143
양천구    15.715789  23.315789  168.878947
영등포구   12.436842  22.589474  196.747368
용산구    11.364706  23.217647  234.970588
은평구    12.423529  26.835294  237.970588
종로구    10.444444  26.044444  290.805556
중구      9.512500  25.875000  308.550000
중랑구    11.447059  26.635294  247.900000

<ipython-input-25-a3e93cab1a14>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  print(addition.groupby('동별(1)').mean())

In [ ]:
 #2022 - 유년부양비, 2022.1 - 노년부양비, 2022.2 - 노령화지수

In [37]:
addmean.rename(columns={'동별(1)':'자치구','2022':'유년부양비','2022.1':'노년부양비','2022.2':'노령화지수'}, inplace=True)
addmean

           유년부양비      노년부양비       노령화지수
동별(1)
강남구    15.717391  23.226087  173.782609
강동구    15.965000  23.200000  174.215000
강북구    10.428571  32.571429  336.078571
강서구    12.466667  25.090476  229.895238
관악구     8.163636  21.795455  293.304545
광진구    10.368750  20.468750  226.293750
구로구    13.405882  24.905882  219.117647
금천구    10.090909  25.509091  260.200000
노원구    13.955000  25.335000  195.720000
도봉구    12.000000  30.720000  265.320000
동대문구   11.233333  25.086667  239.086667
동작구    11.656250  24.018750  231.975000
마포구    12.400000  19.658824  178.841176
서대문구   13.480000  24.480000  198.193333
서초구    18.257895  21.578947  125.952632
성동구    12.338889  22.394444  199.255556
성북구    13.033333  24.128571  211.595238
송파구    15.203571  22.721429  175.582143
양천구    15.715789  23.315789  168.878947
영등포구   12.436842  22.589474  196.747368
용산구    11.364706  23.217647  234.970588
은평구    12.423529  26.835294  237.970588
종로구    10.444444  26.044444  290.805556
중구      9.512500  25.875000  308.550000
중랑구    11.447059  26.635294  247.900000

In [32]:
addmean

In [30]:
addmean = addmean.rename(columns={'동별(1)':'자치구'},inplace=True)
addmean

In [15]:
cluster = cluster.sort_values('자치구')
cluster

    Unnamed: 0   자치구   노인인구수  역개수  무료급식소개수  시설개수
22          22   강남구   81564   21       11    24
24          24   강동구   78191   14        4    31
8            8   강북구   66170    3       11    35
15          15   강서구   96880    9       14    40
20          20   관악구   81848    4        6    29
4            4   광진구   53737   11        2    22
16          16   구로구   74491    7        6    25
17          17   금천구   42226    1        7    18
10          10   노원구   91946   13        3    46
9            9   도봉구   66942    3        0    29
5            5  동대문구   64255    6        2    35
19          19   동작구   67872   12        9    29
13          13   마포구   55533   16       11    29
12          12  서대문구   55502    5        8    23
21          21   서초구   62228   12        5    12
3            3   성동구   47530   14        5    19
7            7   성북구   77293    9       11    28
23          23   송파구  103361   28        1    41
14          14   양천구   72235    5       10    35
18          18  영등포구   63349   11        5    22
2            2   용산구   38478   10        3     7
11          11   은평구   89422   13       10    41
0            0   종로구   27704   15        5     8
1            1    중구   24660   23        2    11
6            6   중랑구   74790    8       11    48

In [16]:
cluster = cluster.drop('Unnamed: 0',axis=1)
cluster

     자치구   노인인구수  역개수  무료급식소개수  시설개수
22   강남구   81564   21       11    24
24   강동구   78191   14        4    31
8    강북구   66170    3       11    35
15   강서구   96880    9       14    40
20   관악구   81848    4        6    29
4    광진구   53737   11        2    22
16   구로구   74491    7        6    25
17   금천구   42226    1        7    18
10   노원구   91946   13        3    46
9    도봉구   66942    3        0    29
5   동대문구   64255    6        2    35
19   동작구   67872   12        9    29
13   마포구   55533   16       11    29
12  서대문구   55502    5        8    23
21   서초구   62228   12        5    12
3    성동구   47530   14        5    19
7    성북구   77293    9       11    28
23   송파구  103361   28        1    41
14   양천구   72235    5       10    35
18  영등포구   63349   11        5    22
2    용산구   38478   10        3     7
11   은평구   89422   13       10    41
0    종로구   27704   15        5     8
1     중구   24660   23        2    11
6    중랑구   74790    8       11    48

In [39]:
cluster.rename(columns={'자치구':'동별(1)'}, inplace=True)

In [40]:
cluster

   동별(1)   노인인구수  역개수  무료급식소개수  시설개수
22   강남구   81564   21       11    24
24   강동구   78191   14        4    31
8    강북구   66170    3       11    35
15   강서구   96880    9       14    40
20   관악구   81848    4        6    29
4    광진구   53737   11        2    22
16   구로구   74491    7        6    25
17   금천구   42226    1        7    18
10   노원구   91946   13        3    46
9    도봉구   66942    3        0    29
5   동대문구   64255    6        2    35
19   동작구   67872   12        9    29
13   마포구   55533   16       11    29
12  서대문구   55502    5        8    23
21   서초구   62228   12        5    12
3    성동구   47530   14        5    19
7    성북구   77293    9       11    28
23   송파구  103361   28        1    41
14   양천구   72235    5       10    35
18  영등포구   63349   11        5    22
2    용산구   38478   10        3     7
11   은평구   89422   13       10    41
0    종로구   27704   15        5     8
1     중구   24660   23        2    11
6    중랑구   74790    8       11    48

In [53]:
hap = pd.merge(left=addmean,right=cluster,how="inner",on="동별(1)")
hap = hap.rename(columns={'동별(1)':'자치구'})
hap

     자치구      유년부양비      노년부양비       노령화지수   노인인구수  역개수  무료급식소개수  시설개수
0    강남구  15.717391  23.226087  173.782609   81564   21       11    24
1    강동구  15.965000  23.200000  174.215000   78191   14        4    31
2    강북구  10.428571  32.571429  336.078571   66170    3       11    35
3    강서구  12.466667  25.090476  229.895238   96880    9       14    40
4    관악구   8.163636  21.795455  293.304545   81848    4        6    29
5    광진구  10.368750  20.468750  226.293750   53737   11        2    22
6    구로구  13.405882  24.905882  219.117647   74491    7        6    25
7    금천구  10.090909  25.509091  260.200000   42226    1        7    18
8    노원구  13.955000  25.335000  195.720000   91946   13        3    46
9    도봉구  12.000000  30.720000  265.320000   66942    3        0    29
10  동대문구  11.233333  25.086667  239.086667   64255    6        2    35
11   동작구  11.656250  24.018750  231.975000   67872   12        9    29
12   마포구  12.400000  19.658824  178.841176   55533   16       11    29
13  서대문구  13.480000  24.480000  198.193333   55502    5        8    23
14   서초구  18.257895  21.578947  125.952632   62228   12        5    12
15   성동구  12.338889  22.394444  199.255556   47530   14        5    19
16   성북구  13.033333  24.128571  211.595238   77293    9       11    28
17   송파구  15.203571  22.721429  175.582143  103361   28        1    41
18   양천구  15.715789  23.315789  168.878947   72235    5       10    35
19  영등포구  12.436842  22.589474  196.747368   63349   11        5    22
20   용산구  11.364706  23.217647  234.970588   38478   10        3     7
21   은평구  12.423529  26.835294  237.970588   89422   13       10    41
22   종로구  10.444444  26.044444  290.805556   27704   15        5     8
23    중구   9.512500  25.875000  308.550000   24660   23        2    11
24   중랑구  11.447059  26.635294  247.900000   74790    8       11    48

In [43]:
import statsmodels.api as sm

In [128]:
!pip install statsmodels

Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (0.14.0)
Requirement already satisfied: numpy>=1.18 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (1.23.5)
Requirement already satisfied: scipy!=1.9.2,>=1.4 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (1.11.3)
Requirement already satisfied: pandas>=1.0 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (1.5.3)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (0.5.3)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (23.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0->statsmodels) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0->statsmodels) (2023.3.post1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.2->statsmodels) (1.16.0)

In [45]:
from statsmodels.formula.api import ols

In [46]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [ ]:
자치구	유년부양비	노년부양비	노령화지수	노인인구수	역개수	무료급식소개수	시설개수

In [56]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [57]:
X_train = hap[['유년부양비','노년부양비','노령화지수','노인인구수','역개수','무료급식소개수','시설개수']]

In [61]:
def feature_engineering_XbyVIF(X_train):
  vif = pd.DataFrame()
  vif["VIF_Factor"] = [variance_inflation_factor(X_train.values, i)
    for i in range(X_train.shape[1])]
  vif['Feature'] = X_train.columns
  return vif

In [62]:
vif = feature_engineering_XbyVIF(X_train)
print(vif) #wow

   VIF_Factor  Feature
0  114.074133    유년부양비
1  393.234698    노년부양비
2  144.991717    노령화지수
3   57.448984    노인인구수
4    5.725103      역개수
5    4.624975  무료급식소개수
6   33.334659     시설개수

In [ ]:
#scaling 진행
#minmax , standard

In [67]:
df = hap
df

,자치구,유년부양비,노년부양비,노령화지수,노인인구수,역개수,무료급식소개수,시설개수,intercept
0,강남구,15.717391,23.226087,173.782609,81564,21,11,24,1
1,강동구,15.965000,23.200000,174.215000,78191,14,4,31,1
2,강북구,10.428571,32.571429,336.078571,66170,3,11,35,1
3,강서구,12.466667,25.090476,229.895238,96880,9,14,40,1
4,관악구,8.163636,21.795455,293.304545,81848,4,6,29,1
5,광진구,10.368750,20.468750,226.293750,53737,11,2,22,1
6,구로구,13.405882,24.905882,219.117647,74491,7,6,25,1
7,금천구,10.090909,25.509091,260.200000,42226,1,7,18,1
8,노원구,13.955000,25.335000,195.720000,91946,13,3,46,1
9,도봉구,12.000000,30.720000,265.320000,66942,3,0,29,1
10,동대문구,11.233333,25.086667,239.086667,64255,6,2,35,1
11,동작구,11.656250,24.018750,231.975000,67872,12,9,29,1
12,마포구,12.400000,19.658824,178.841176,55533,16,11,29,1
13,서대문구,13.480000,24.480000,198.193333,55502,5,8,23,1
14,서초구,18.257895,21.578947,125.952632,62228,12,5,12,1
15,성동구,12.338889,22.394444,199.255556,47530,14,5,19,1
16,성북구,13.033333,24.128571,211.595238,77293,9,11,28,1
17,송파구,15.203571,22.721429,175.582143,103361,28,1,41,1
18,양천구,15.715789,23.315789,168.878947,72235,5,10,35,1
19,영등포구,12.436842,22.589474,196.747368,63349,11,5,22,1
20,용산구,11.364706,23.217647,234.970588,38478,10,3,7,1
21,은평구,12.423529,26.835294,237.970588,89422,13,10,41,1
22,종로구,10.444444,26.044444,290.805556,27704,15,5,8,1
23,중구,9.512500,25.875000,308.550000,24660,23,2,11,1
24,중랑구,11.447059,26.635294,247.900000,74790,8,11,48,1

In [65]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [71]:
df2 = df.drop('자치구',axis=1)
df2

        유년부양비      노년부양비       노령화지수   노인인구수  역개수  무료급식소개수  시설개수  intercept
0   15.717391  23.226087  173.782609   81564   21       11    24          1
1   15.965000  23.200000  174.215000   78191   14        4    31          1
2   10.428571  32.571429  336.078571   66170    3       11    35          1
3   12.466667  25.090476  229.895238   96880    9       14    40          1
4    8.163636  21.795455  293.304545   81848    4        6    29          1
5   10.368750  20.468750  226.293750   53737   11        2    22          1
6   13.405882  24.905882  219.117647   74491    7        6    25          1
7   10.090909  25.509091  260.200000   42226    1        7    18          1
8   13.955000  25.335000  195.720000   91946   13        3    46          1
9   12.000000  30.720000  265.320000   66942    3        0    29          1
10  11.233333  25.086667  239.086667   64255    6        2    35          1
11  11.656250  24.018750  231.975000   67872   12        9    29          1
12  12.400000  19.658824  178.841176   55533   16       11    29          1
13  13.480000  24.480000  198.193333   55502    5        8    23          1
14  18.257895  21.578947  125.952632   62228   12        5    12          1
15  12.338889  22.394444  199.255556   47530   14        5    19          1
16  13.033333  24.128571  211.595238   77293    9       11    28          1
17  15.203571  22.721429  175.582143  103361   28        1    41          1
18  15.715789  23.315789  168.878947   72235    5       10    35          1
19  12.436842  22.589474  196.747368   63349   11        5    22          1
20  11.364706  23.217647  234.970588   38478   10        3     7          1
21  12.423529  26.835294  237.970588   89422   13       10    41          1
22  10.444444  26.044444  290.805556   27704   15        5     8          1
23   9.512500  25.875000  308.550000   24660   23        2    11          1
24  11.447059  26.635294  247.900000   74790    8       11    48          1

In [72]:
# MinMaxScaler 선언 및 Fitting
mMscaler = MinMaxScaler()
mMscaler.fit(df2)

MinMaxScaler()

In [74]:
scaler = MinMaxScaler()
# min-max 값 학습
minmax_scaled = scaler.fit_transform(X_train)

In [83]:
mms = round(pd.DataFrame(minmax_scaled),2)
mms

       0     1     2     3     4     5     6
0   0.75  0.28  0.23  0.72  0.74  0.79  0.41
1   0.77  0.27  0.23  0.68  0.48  0.29  0.59
2   0.22  1.00  1.00  0.53  0.07  0.79  0.68
3   0.43  0.42  0.49  0.92  0.30  1.00  0.80
4   0.00  0.17  0.80  0.73  0.11  0.43  0.54
5   0.22  0.06  0.48  0.37  0.37  0.14  0.37
6   0.52  0.41  0.44  0.63  0.22  0.43  0.44
7   0.19  0.45  0.64  0.22  0.00  0.50  0.27
8   0.57  0.44  0.33  0.85  0.44  0.21  0.95
9   0.38  0.86  0.66  0.54  0.07  0.00  0.54
10  0.30  0.42  0.54  0.50  0.19  0.14  0.68
11  0.35  0.34  0.50  0.55  0.41  0.64  0.54
12  0.42  0.00  0.25  0.39  0.56  0.79  0.54
13  0.53  0.37  0.34  0.39  0.15  0.57  0.39
14  1.00  0.15  0.00  0.48  0.41  0.36  0.12
15  0.41  0.21  0.35  0.29  0.48  0.36  0.29
16  0.48  0.35  0.41  0.67  0.30  0.79  0.51
17  0.70  0.24  0.24  1.00  1.00  0.07  0.83
18  0.75  0.28  0.20  0.60  0.15  0.71  0.68
19  0.42  0.23  0.34  0.49  0.37  0.36  0.37
20  0.32  0.28  0.52  0.18  0.33  0.21  0.00
21  0.42  0.56  0.53  0.82  0.44  0.71  0.83
22  0.23  0.49  0.78  0.04  0.52  0.36  0.02
23  0.13  0.48  0.87  0.00  0.81  0.14  0.10
24  0.33  0.54  0.58  0.64  0.26  0.79  1.00

In [88]:
mms.rename(columns={'0':'유년부양비','1':'노년부양비','2':'노령화지수','3':'노인인구수','4':'역개수','5':'무료급식소개수','6':'시설개수'})

       0     1     2     3     4     5     6
0   0.75  0.28  0.23  0.72  0.74  0.79  0.41
1   0.77  0.27  0.23  0.68  0.48  0.29  0.59
2   0.22  1.00  1.00  0.53  0.07  0.79  0.68
3   0.43  0.42  0.49  0.92  0.30  1.00  0.80
4   0.00  0.17  0.80  0.73  0.11  0.43  0.54
5   0.22  0.06  0.48  0.37  0.37  0.14  0.37
6   0.52  0.41  0.44  0.63  0.22  0.43  0.44
7   0.19  0.45  0.64  0.22  0.00  0.50  0.27
8   0.57  0.44  0.33  0.85  0.44  0.21  0.95
9   0.38  0.86  0.66  0.54  0.07  0.00  0.54
10  0.30  0.42  0.54  0.50  0.19  0.14  0.68
11  0.35  0.34  0.50  0.55  0.41  0.64  0.54
12  0.42  0.00  0.25  0.39  0.56  0.79  0.54
13  0.53  0.37  0.34  0.39  0.15  0.57  0.39
14  1.00  0.15  0.00  0.48  0.41  0.36  0.12
15  0.41  0.21  0.35  0.29  0.48  0.36  0.29
16  0.48  0.35  0.41  0.67  0.30  0.79  0.51
17  0.70  0.24  0.24  1.00  1.00  0.07  0.83
18  0.75  0.28  0.20  0.60  0.15  0.71  0.68
19  0.42  0.23  0.34  0.49  0.37  0.36  0.37
20  0.32  0.28  0.52  0.18  0.33  0.21  0.00
21  0.42  0.56  0.53  0.82  0.44  0.71  0.83
22  0.23  0.49  0.78  0.04  0.52  0.36  0.02
23  0.13  0.48  0.87  0.00  0.81  0.14  0.10
24  0.33  0.54  0.58  0.64  0.26  0.79  1.00

In [90]:
# min-max 값 학습
minmax_scaled = scaler.fit_transform(mms)
minmax_scaled

array([[0.75, 0.28, 0.23, 0.72, 0.74, 0.79, 0.41],
       [0.77, 0.27, 0.23, 0.68, 0.48, 0.29, 0.59],
       [0.22, 1.  , 1.  , 0.53, 0.07, 0.79, 0.68],
       [0.43, 0.42, 0.49, 0.92, 0.3 , 1.  , 0.8 ],
       [0.  , 0.17, 0.8 , 0.73, 0.11, 0.43, 0.54],
       [0.22, 0.06, 0.48, 0.37, 0.37, 0.14, 0.37],
       [0.52, 0.41, 0.44, 0.63, 0.22, 0.43, 0.44],
       [0.19, 0.45, 0.64, 0.22, 0.  , 0.5 , 0.27],
       [0.57, 0.44, 0.33, 0.85, 0.44, 0.21, 0.95],
       [0.38, 0.86, 0.66, 0.54, 0.07, 0.  , 0.54],
       [0.3 , 0.42, 0.54, 0.5 , 0.19, 0.14, 0.68],
       [0.35, 0.34, 0.5 , 0.55, 0.41, 0.64, 0.54],
       [0.42, 0.  , 0.25, 0.39, 0.56, 0.79, 0.54],
       [0.53, 0.37, 0.34, 0.39, 0.15, 0.57, 0.39],
       [1.  , 0.15, 0.  , 0.48, 0.41, 0.36, 0.12],
       [0.41, 0.21, 0.35, 0.29, 0.48, 0.36, 0.29],
       [0.48, 0.35, 0.41, 0.67, 0.3 , 0.79, 0.51],
       [0.7 , 0.24, 0.24, 1.  , 1.  , 0.07, 0.83],
       [0.75, 0.28, 0.2 , 0.6 , 0.15, 0.71, 0.68],
       [0.42, 0.23, 0.34, 0.49, 0.37, 0.36, 0.37],
       [0.32, 0.28, 0.52, 0.18, 0.33, 0.21, 0.  ],
       [0.42, 0.56, 0.53, 0.82, 0.44, 0.71, 0.83],
       [0.23, 0.49, 0.78, 0.04, 0.52, 0.36, 0.02],
       [0.13, 0.48, 0.87, 0.  , 0.81, 0.14, 0.1 ],
       [0.33, 0.54, 0.58, 0.64, 0.26, 0.79, 1.  ]])

In [ ]:
def feature_engineering_XbyVIF(X_train):
  vif = pd.DataFrame()
  vif["VIF_Factor"] = [variance_inflation_factor(X_train.values, i)
    for i in range(X_train.shape[1])]
  vif['Feature'] = X_train.columns
  return vif

In [91]:
vif = feature_engineering_XbyVIF(mms)
print(vif)  #min-max scaling 후의 결과. 훨씬 낫지만 노년부양비, 노령화지수, 노인인구수,시설개수는 여전히 10을 넘는다.

   VIF_Factor  Feature
0   10.249452        0
1   11.589788        1
2   12.042556        2
3   24.358003        3
4    4.939001        4
5    4.585355        5
6   18.095033        6

In [ ]:
#X_train = hap[['유년부양비','노년부양비','노령화지수','노인인구수','역개수','무료급식소개수','시설개수']]

In [96]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [100]:
standard_scaled = scaler.fit_transform(X_train)
ss = round(pd.DataFrame(standard_scaled),2)
ss

       0     1     2     3     4     5     6
0   1.40 -0.44 -1.06  0.77  1.59  1.18 -0.32
1   1.51 -0.45 -1.05  0.60  0.48 -0.65  0.32
2  -0.93  2.91  2.31 -0.01 -1.25  1.18  0.68
3  -0.03  0.23  0.11  1.55 -0.30  1.97  1.13
4  -1.93 -0.95  1.42  0.79 -1.09 -0.13  0.14
5  -0.96 -1.43  0.03 -0.64  0.01 -1.17 -0.50
6   0.38  0.16 -0.12  0.41 -0.62 -0.13 -0.22
7  -1.08  0.38  0.73 -1.22 -1.56  0.14 -0.86
8   0.62  0.32 -0.60  1.30  0.33 -0.91  1.68
9  -0.24  2.25  0.84  0.03 -1.25 -1.70  0.14
10 -0.58  0.23  0.30 -0.10 -0.77 -1.17  0.68
11 -0.39 -0.16  0.15  0.08  0.17  0.66  0.14
12 -0.06 -1.72 -0.95 -0.55  0.80  1.18  0.14
13  0.41  0.01 -0.55 -0.55 -0.93  0.40 -0.41
14  2.52 -1.03 -2.05 -0.21  0.17 -0.39 -1.40
15 -0.09 -0.74 -0.53 -0.95  0.48 -0.39 -0.77
16  0.22 -0.12 -0.27  0.55 -0.30  1.18  0.05
17  1.17 -0.62 -1.02  1.87  2.69 -1.44  1.22
18  1.40 -0.41 -1.16  0.30 -0.93  0.92  0.68
19 -0.05 -0.67 -0.58 -0.15  0.01 -0.39 -0.50
20 -0.52 -0.44  0.21 -1.41 -0.14 -0.91 -1.85
21 -0.05  0.85  0.27  1.17  0.33  0.92  1.22
22 -0.92  0.57  1.37 -1.95  0.64 -0.39 -1.76
23 -1.33  0.51  1.74 -2.11  1.90 -1.17 -1.49
24 -0.48  0.78  0.48  0.43 -0.46  1.18  1.86

In [101]:
vif = feature_engineering_XbyVIF(ss)
print(vif) #유년부양비, 노령화지수 제외 모두 괜찮다!

   VIF_Factor  Feature
0   15.961401        0
1    7.535291        1
2   23.001846        2
3    4.882604        3
4    1.511825        4
5    1.200543        5
6    5.131384        6

In [95]:
#X_train = hap[['유년부양비','노년부양비','노령화지수','노인인구수','역개수','무료급식소개수','시설개수']]

In [102]:
from sklearn.preprocessing import RobustScaler

In [103]:
scaler = RobustScaler()
robust_scaled = scaler.fit_transform(X_train)
rs = round(pd.DataFrame(robust_scaled),2)
rs

       0     1     2     3     4     5     6
0   1.48 -0.32 -1.01  0.64  1.25  0.71 -0.38
1   1.59 -0.33 -1.00  0.50  0.38 -0.29  0.15
2  -0.88  3.03  2.10 -0.03 -1.00  0.71  0.46
3   0.03  0.35  0.07  1.32 -0.25  1.14  0.85
4  -1.89 -0.84  1.28  0.66 -0.88  0.00  0.00
5  -0.90 -1.31  0.00 -0.58  0.00 -0.57 -0.54
6   0.45  0.28 -0.14  0.33 -0.50  0.00 -0.31
7  -1.03  0.50  0.65 -1.09 -1.25  0.14 -0.85
8   0.69  0.43 -0.59  1.10  0.25 -0.43  1.31
9  -0.18  2.36  0.75  0.00 -1.00 -0.86  0.00
10 -0.52  0.34  0.25 -0.12 -0.62 -0.57  0.46
11 -0.33 -0.04  0.11  0.04  0.12  0.43  0.00
12  0.00 -1.60 -0.91 -0.50  0.62  0.71  0.00
13  0.48  0.13 -0.54 -0.50 -0.75  0.29 -0.46
14  2.61 -0.91 -1.92 -0.21  0.12 -0.14 -1.31
15 -0.03 -0.62 -0.52 -0.86  0.38 -0.14 -0.77
16  0.28  0.00 -0.28  0.46 -0.25  0.71 -0.08
17  1.25 -0.50 -0.97  1.61  2.12 -0.71  0.92
18  1.48 -0.29 -1.10  0.23 -0.75  0.57  0.46
19  0.02 -0.55 -0.57 -0.16  0.00 -0.14 -0.54
20 -0.46 -0.33  0.17 -1.25 -0.12 -0.43 -1.69
21  0.01  0.97  0.22  0.99  0.25  0.57  0.92
22 -0.87  0.69  1.24 -1.73  0.50 -0.14 -1.62
23 -1.29  0.63  1.58 -1.86  1.50 -0.57 -1.38
24 -0.42  0.90  0.41  0.35 -0.38  0.71  1.46

In [104]:
vif = feature_engineering_XbyVIF(rs)
print(vif) #유년부양비, 노령화지수 제외 모두 괜찮다!

   VIF_Factor  Feature
0   14.829574        0
1    6.625452        1
2   20.941981        2
3    4.655385        3
4    1.467256        4
5    1.162557        5
6    4.609143        6

In [ ]:
#X_train = hap[['유년부양비','노년부양비','노령화지수','노인인구수','역개수','무료급식소개수','시설개수']]