In [9]:
import pandas as pd
survey = pd.read_csv('/content/설문 통합.csv',encoding='cp949')
survey.head(5)

,Unnamed: 0,문항 1,문항 2,문항 3,문항 4,문항 5,문항 6,문항 7,문항 8,문항 9,문항 10
0,1번,0.500,0.333,2.000,1.000,0.333,1.0,0.500,0.333,0.500,0.333
1,2번,3.000,0.333,3.000,0.500,2.000,1.0,0.500,0.333,1.000,0.500
2,3번,2.000,0.500,0.333,0.333,2.000,2.0,0.500,1.000,0.333,0.500
3,4번,0.333,0.333,0.500,2.000,3.000,0.5,1.000,0.500,0.333,0.500
4,5번,2.000,0.500,2.000,0.500,0.500,3.0,0.333,3.000,0.500,0.333

In [10]:
import numpy as np
from scipy.stats.mstats import gmean

In [11]:
survey = survey.drop(['Unnamed: 0'],axis=1)
survey

     문항 1   문항 2  문항 3    문항 4   문항 5   문항 6  문항 7   문항 8    문항 9    문항 10
0   0.500  0.333  2.000  1.000  0.333  1.000  0.500  0.333   0.500   0.333
1   3.000  0.333  3.000  0.500  2.000  1.000  0.500  0.333   1.000   0.500
2   2.000  0.500  0.333  0.333  2.000  2.000  0.500  1.000   0.333   0.500
3   0.333  0.333  0.500  2.000  3.000  0.500  1.000  0.500   0.333   0.500
4   2.000  0.500  2.000  0.500  0.500  3.000  0.333  3.000   0.500   0.333
5   1.000  2.000  3.000  0.333  0.333  3.000  3.000  2.000   2.000   0.333
6   1.000  2.000  0.500  0.333  2.000  3.000  3.000  2.000   1.000   0.333
7   2.000  1.000  0.333  1.000  1.000  1.000  0.333  3.000   0.333   0.500
8   0.500  0.333  0.333  0.500  3.000  0.500  0.333  0.500   0.333   0.333
9   3.000  0.500  0.500  3.000  0.333  0.333  1.000  0.333   0.333   0.333
10  3.000  0.333  0.333  0.500  0.500  2.000  0.500  2.000   1.000   0.333
11  0.333  0.500  1.000  3.000  0.333  1.000  1.000  0.500   0.500   0.500
12  1.000  0.500  1.000  2.000  0.333  5.000  0.500  1.000   1.000   0.333
13  0.500  3.000  2.000  0.500  1.000  0.500  0.333  0.333   0.500   1.000
14  0.500  2.000  2.000  3.000  3.000  0.500  0.333  0.333   1.000   0.333
15  2.000  3.000  0.500  0.333  2.000  3.000  0.333  2.000   1.000   0.500
16  0.333  3.000  3.000  1.000  0.333  0.333  1.000  0.500   0.333   0.333
17  1.000  0.500  3.000  0.500  2.000  1.000  2.000  2.000   0.500   0.333
18  0.500  3.000  0.333  1.000  0.333  2.000  3.000  0.500   3.000   0.500
19  2.000  0.333  1.000  0.333  0.333  0.500  0.500  0.333   2.000   0.333
20  0.333  0.333  0.333  0.333  5.000  0.333  5.000  0.333   0.333   0.500
21  3.000  3.000  3.000  3.000  0.333  3.000  0.333  3.000   0.333   0.333
22  0.500  0.500  0.333  1.000  2.000  2.000  1.000  1.000   2.000   2.000
23  1.000  1.000  1.000  0.500  2.000  2.000  1.000  0.500   2.000   2.000
24  0.333  5.000  5.000  0.333  3.000  3.000  0.333  3.000   0.333   0.333
25  3.000  3.000  3.000  0.333  3.000  3.000  0.333  0.333   0.333   0.333
26  5.000  7.000  7.000  8.000  9.000  3.000  9.000  8.000  10.000  15.000
27  6.000  7.000  4.000  7.000  2.000  5.000  6.000  6.000   5.000   8.000
28  5.000  2.000  4.000  5.000  2.000  5.000  6.000  3.000   6.000   1.000
29  5.000  3.000  4.000  2.000  7.000  5.000  1.000  5.000   4.000   2.000
30  5.000  6.000  6.000  4.000  5.000  7.000  3.000  4.000   1.000   0.000

In [ ]:
survey = survey.iloc[:26]
survey

     문항 1   문항 2  문항 3    문항 4   문항 5   문항 6  문항 7   문항 8   문항 9   문항 10
0   0.500  0.333  2.000  1.000  0.333  1.000  0.500  0.333  0.500  0.333
1   3.000  0.333  3.000  0.500  2.000  1.000  0.500  0.333  1.000  0.500
2   2.000  0.500  0.333  0.333  2.000  2.000  0.500  1.000  0.333  0.500
3   0.333  0.333  0.500  2.000  3.000  0.500  1.000  0.500  0.333  0.500
4   2.000  0.500  2.000  0.500  0.500  3.000  0.333  3.000  0.500  0.333
5   1.000  2.000  3.000  0.333  0.333  3.000  3.000  2.000  2.000  0.333
6   1.000  2.000  0.500  0.333  2.000  3.000  3.000  2.000  1.000  0.333
7   2.000  1.000  0.333  1.000  1.000  1.000  0.333  3.000  0.333  0.500
8   0.500  0.333  0.333  0.500  3.000  0.500  0.333  0.500  0.333  0.333
9   3.000  0.500  0.500  3.000  0.333  0.333  1.000  0.333  0.333  0.333
10  3.000  0.333  0.333  0.500  0.500  2.000  0.500  2.000  1.000  0.333
11  0.333  0.500  1.000  3.000  0.333  1.000  1.000  0.500  0.500  0.500
12  1.000  0.500  1.000  2.000  0.333  5.000  0.500  1.000  1.000  0.333
13  0.500  3.000  2.000  0.500  1.000  0.500  0.333  0.333  0.500  1.000
14  0.500  2.000  2.000  3.000  3.000  0.500  0.333  0.333  1.000  0.333
15  2.000  3.000  0.500  0.333  2.000  3.000  0.333  2.000  1.000  0.500
16  0.333  3.000  3.000  1.000  0.333  0.333  1.000  0.500  0.333  0.333
17  1.000  0.500  3.000  0.500  2.000  1.000  2.000  2.000  0.500  0.333
18  0.500  3.000  0.333  1.000  0.333  2.000  3.000  0.500  3.000  0.500
19  2.000  0.333  1.000  0.333  0.333  0.500  0.500  0.333  2.000  0.333
20  0.333  0.333  0.333  0.333  5.000  0.333  5.000  0.333  0.333  0.500
21  3.000  3.000  3.000  3.000  0.333  3.000  0.333  3.000  0.333  0.333
22  0.500  0.500  0.333  1.000  2.000  2.000  1.000  1.000  2.000  2.000
23  1.000  1.000  1.000  0.500  2.000  2.000  1.000  0.500  2.000  2.000
24  0.333  5.000  5.000  0.333  3.000  3.000  0.333  3.000  0.333  0.333
25  3.000  3.000  3.000  0.333  3.000  3.000  0.333  0.333  0.333  0.333

In [17]:
survey  = survey.iloc[:26]
survey

     문항 1   문항 2  문항 3    문항 4   문항 5   문항 6  문항 7   문항 8   문항 9   문항 10
0   0.500  0.333  2.000  1.000  0.333  1.000  0.500  0.333  0.500  0.333
1   3.000  0.333  3.000  0.500  2.000  1.000  0.500  0.333  1.000  0.500
2   2.000  0.500  0.333  0.333  2.000  2.000  0.500  1.000  0.333  0.500
3   0.333  0.333  0.500  2.000  3.000  0.500  1.000  0.500  0.333  0.500
4   2.000  0.500  2.000  0.500  0.500  3.000  0.333  3.000  0.500  0.333
5   1.000  2.000  3.000  0.333  0.333  3.000  3.000  2.000  2.000  0.333
6   1.000  2.000  0.500  0.333  2.000  3.000  3.000  2.000  1.000  0.333
7   2.000  1.000  0.333  1.000  1.000  1.000  0.333  3.000  0.333  0.500
8   0.500  0.333  0.333  0.500  3.000  0.500  0.333  0.500  0.333  0.333
9   3.000  0.500  0.500  3.000  0.333  0.333  1.000  0.333  0.333  0.333
10  3.000  0.333  0.333  0.500  0.500  2.000  0.500  2.000  1.000  0.333
11  0.333  0.500  1.000  3.000  0.333  1.000  1.000  0.500  0.500  0.500
12  1.000  0.500  1.000  2.000  0.333  5.000  0.500  1.000  1.000  0.333
13  0.500  3.000  2.000  0.500  1.000  0.500  0.333  0.333  0.500  1.000
14  0.500  2.000  2.000  3.000  3.000  0.500  0.333  0.333  1.000  0.333
15  2.000  3.000  0.500  0.333  2.000  3.000  0.333  2.000  1.000  0.500
16  0.333  3.000  3.000  1.000  0.333  0.333  1.000  0.500  0.333  0.333
17  1.000  0.500  3.000  0.500  2.000  1.000  2.000  2.000  0.500  0.333
18  0.500  3.000  0.333  1.000  0.333  2.000  3.000  0.500  3.000  0.500
19  2.000  0.333  1.000  0.333  0.333  0.500  0.500  0.333  2.000  0.333
20  0.333  0.333  0.333  0.333  5.000  0.333  5.000  0.333  0.333  0.500
21  3.000  3.000  3.000  3.000  0.333  3.000  0.333  3.000  0.333  0.333
22  0.500  0.500  0.333  1.000  2.000  2.000  1.000  1.000  2.000  2.000
23  1.000  1.000  1.000  0.500  2.000  2.000  1.000  0.500  2.000  2.000
24  0.333  5.000  5.000  0.333  3.000  3.000  0.333  3.000  0.333  0.333
25  3.000  3.000  3.000  0.333  3.000  3.000  0.333  0.333  0.333  0.333

In [20]:
survey = survey.astype('float')

In [23]:
# 각 컬럼의 기하평균을 계산하여 리스트에 저장
geo_mean_list = []
for i in survey:
    geo_mean_list.append(gmean(survey[i]))

In [ ]:
	#가중치
#기초생활수급자인원	0.302868
#노년부양비	0.178305
#고령내국인전체	0.112779
#노령화지수	0.191392
#무료급식소개수	0.214656

In [27]:
# 기하평균 출력
print('기하평균 (Geometric mean)\n')
for i,j in zip(survey, geo_mean_list):
    #print('{} : {}'.format(i, j))
    print('{} : {}'.format(i, round(j,3)))  # 소수점 3 자리수

기하평균 (Geometric mean)

문항 1 : 0.974
문항 2 : 0.916
문항 3  : 1.02
문항 4 : 0.739
문항 5 : 1.026
문항 6 : 1.26
문항 7  : 0.722
문항 8  : 0.822
문항 9  : 0.665
문항 10 : 0.452

In [39]:
a = 0.916 #수급_노인부양비
b = 0.974  #수급-고령
c = 1.02 #수급 _ 노령화지수
d = 0.739 #수급 - 무료급식소
e = 1.026 #고령 - 부양비
h = 1.26 #고령 - 노령화지수
i = 0.722 #고령 - 무료급식소
f = 0.822 #부양비 - 노령화지수
g = 0.665 #부양비  -무료급식소
j = 0.452 #노령화지수 - 무료급식

In [40]:
# 기하평균을 대표값으로 쌍대 비교 행렬을 구하고 np01라고 부르기로 합니다.
np01 = np.array([[1, a, b,c,d], [1/a, 1, e,f,g],[1/b, 1/c,1,h,i],[1/d, 1/e,1/f,1,j], [1/g, 1/h,1/i,1/j,1]])
# np01이 어떻게 생겼는지 확인합니다.
print(np01)

[[1.         0.916      0.974      1.02       0.739     ]
 [1.09170306 1.         1.026      0.822      0.665     ]
 [1.02669405 0.98039216 1.         1.26       0.722     ]
 [1.35317997 0.97465887 1.21654501 1.         0.452     ]
 [1.5037594  0.79365079 1.38504155 2.21238938 1.        ]]

In [43]:
ssang = pd.read_csv('/content/AHP용.csv')
ssang

  Unnamed: 0  기초생활수급자인원     노년부양비   고령내국인전체     노령화지수  무료급식소개수
0  기초생활수급자인원   1.000000  0.916000  0.974000  1.020000    0.739
1      노년부양비   1.091703  1.000000  1.026000  0.822000    0.665
2    고령내국인전체   1.026694  0.980392  1.000000  1.260000    0.722
3      노령화지수   1.353180  0.974659  1.216545  1.000000    0.452
4    무료급식소개수   1.503759  0.793651  1.385042  2.212389    1.000

In [44]:
ssang = ssang.drop(['Unnamed: 0'],axis=1)
ssang

   기초생활수급자인원     노년부양비   고령내국인전체     노령화지수  무료급식소개수
0   1.000000  0.916000  0.974000  1.020000    0.739
1   1.091703  1.000000  1.026000  0.822000    0.665
2   1.026694  0.980392  1.000000  1.260000    0.722
3   1.353180  0.974659  1.216545  1.000000    0.452
4   1.503759  0.793651  1.385042  2.212389    1.000

In [45]:
# 데이터프레임의 컬럼수 파악
colums_cnt = len(ssang.columns)
colums_cnt

5

In [46]:
# 각 컬럼의 기하평균을 계산하여 리스트에 저장
ssang_mean_list = []
for i in ssang:
    ssang_mean_list.append(gmean(ssang[i]))

In [47]:
# 기하평균 출력
print('기하평균 (Geometric mean)\n')
for i,j in zip(ssang, ssang_mean_list):
    print('{} : {}'.format(i, j))
    #print('{} : {}'.format(i, round(j,3)))  # 소수점 3 자리수

기하평균 (Geometric mean)

기초생활수급자인원 : 1.1792771882963793
노년부양비 : 0.9297270765132472
고령내국인전체 : 1.1098376668507635
노령화지수 : 1.1850613122603488
무료급식소개수 : 0.6934710623102154

In [48]:
# 데이터프레임에 기하평균값 추가
ss = ssang.append(pd.Series(ssang_mean_list, index=ssang.columns),ignore_index=True)
ss

<ipython-input-48-cd4b2e49a8f7>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ss = ssang.append(pd.Series(ssang_mean_list, index=ssang.columns),ignore_index=True)

   기초생활수급자인원     노년부양비   고령내국인전체     노령화지수   무료급식소개수
0   1.000000  0.916000  0.974000  1.020000  0.739000
1   1.091703  1.000000  1.026000  0.822000  0.665000
2   1.026694  0.980392  1.000000  1.260000  0.722000
3   1.353180  0.974659  1.216545  1.000000  0.452000
4   1.503759  0.793651  1.385042  2.212389  1.000000
5   1.179277  0.929727  1.109838  1.185061  0.693471

In [49]:
# 가중치 계산을 위하여 기하평균의 합을 구함
ssang_mean_sum = sum(ssang_mean_list)
ssang_mean_sum

5.097374306230955

In [50]:
# 각 컬럼의 가중치를 계산하여 리스트에 저장
weight_list = []
for i in range(colums_cnt):
    weight_list.append(ssang_mean_list[i]/ssang_mean_sum)

In [51]:
# 기하평균 출력
print('가중치 (Weights)\n')
for i,j in zip(ss, weight_list):
    print('{} : {}'.format(i, j))
    #print('{} : {}'.format(i, round(j,3)))  # 소수점 3 자리수

가중치 (Weights)

기초생활수급자인원 : 0.2313499298756319
노년부양비 : 0.1823933304989517
고령내국인전체 : 0.2177273239467846
노령화지수 : 0.23248465603394036
무료급식소개수 : 0.13604475964469132

In [52]:
# 가중치 합 확인
su_ = sum(list(weight_list))
print(su_)

0.9999999999999999

In [53]:
ss = ss.append(pd.Series(weight_list, index=ss.columns),ignore_index=True)
ss

<ipython-input-53-5ce2691a996a>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ss = ss.append(pd.Series(weight_list, index=ss.columns),ignore_index=True)

   기초생활수급자인원     노년부양비   고령내국인전체     노령화지수   무료급식소개수
0   1.000000  0.916000  0.974000  1.020000  0.739000
1   1.091703  1.000000  1.026000  0.822000  0.665000
2   1.026694  0.980392  1.000000  1.260000  0.722000
3   1.353180  0.974659  1.216545  1.000000  0.452000
4   1.503759  0.793651  1.385042  2.212389  1.000000
5   1.179277  0.929727  1.109838  1.185061  0.693471
6   0.231350  0.182393  0.217727  0.232485  0.136045

In [54]:
# 데이터프레임을 csv로 저장
ss.to_csv('AHP_가중치산정_결과.csv',index=True , sep=',', encoding='cp949')

In [41]:
# 정규화 행렬들을 담을 리스트 공간을 만들어 둡니다.
np_norm_list = []
# 가중치들을 담을 리스트 공간을 만들어 둡니다.
weights_list = []

In [42]:
# 쌍대 비교 행렬들을 i번째 순서에 따라 처리할 반복문을 만들 것입니다:
for i, np_matrix in enumerate(np01):
	# 쌍대 비교 행렬의 열의 합을 계산합니다.
	col_sums = np_matrix.sum(axis=0)
	# 구한 열의 합을 이용해 쌍대 비교 행렬을 정규화 행렬로 변환합니다.
	np_norm = np_matrix / col_sums
	# 각 정규화 행렬을 변환할 때마다 앞서 만든 리스트 공간에 덧붙입니다.
	np_norm_list.append(np_norm)
	# 정규화 행렬의 행의 평균을 계산합니다.
	row_avg = np_norm.mean(axis=1)
	# 계산한 상품별 가중치를 앞서 만든 리스트 공간에 덧붙입니다.
	weights_list.append(row_avg)

AxisError: ignored

In [ ]:
# 쌍대 비교 행렬들의 리스트를 만듭니다.
np_list = []
# i가 0부터 24까지 6씩 증분되는 반복문을 만듭니다.
for i in range(0, 24, 6):
    # 데이터의 0+0열, 6+0열, 12+0열, 18+0열의 값들의 기하평균을 각각 구하고 a라 부르기로 합니다.
    a = gmean(df01.iloc[:, i + 0])
    # 데이터의 0+2열, 6+2열, 12+2열, 18+2열의 값들의 기하평균을 각각 구하고 b라 부르기로 합니다.
    b = gmean(df01.iloc[:, i + 2])
    # 데이터의 0+4열, 6+4열, 12+4열, 18+4열의 값들의 기하평균을 각각 구하고 c라 부르기로 합니다.
    c = gmean(df01.iloc[:, i + 4])
    # 매 반복 시기마다 구한 쌍대 비교 행렬들은 리스트 안에 첨부합니다.
    np_list.append(np.array([[1, a, b], [1/a, 1, c], [1/b, 1/c, 1]]))
# 쌍대 비교 행렬들의 이름을 번호 순으로 지어줍니다.
np01, np02, np03, np04 = np_list

In [26]:
geo_mean_list.fo

[0.9735053964320753,
 0.9164385579063449,
 1.0195667415792815,
 0.738877854780849,
 1.0261720170872768,
 1.2596114381763936,
 0.7223335137384548,
 0.8220248704343436,
 0.665422445304144,
 0.4518752940562179]

In [28]:
# 데이터프레임에 기하평균값 추가
survey = survey.append(pd.Series(geo_mean_list, index=survey.columns),ignore_index=True)
survey

<ipython-input-28-0b09441f38ce>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  survey = survey.append(pd.Series(geo_mean_list, index=survey.columns),ignore_index=True)

,문항 1,문항 2,문항 3,문항 4,문항 5,문항 6,문항 7,문항 8,문항 9,문항 10
0,0.500000,0.333000,2.000000,1.000000,0.333000,1.000000,0.500000,0.333000,0.500000,0.333000
1,3.000000,0.333000,3.000000,0.500000,2.000000,1.000000,0.500000,0.333000,1.000000,0.500000
2,2.000000,0.500000,0.333000,0.333000,2.000000,2.000000,0.500000,1.000000,0.333000,0.500000
3,0.333000,0.333000,0.500000,2.000000,3.000000,0.500000,1.000000,0.500000,0.333000,0.500000
4,2.000000,0.500000,2.000000,0.500000,0.500000,3.000000,0.333000,3.000000,0.500000,0.333000
5,1.000000,2.000000,3.000000,0.333000,0.333000,3.000000,3.000000,2.000000,2.000000,0.333000
6,1.000000,2.000000,0.500000,0.333000,2.000000,3.000000,3.000000,2.000000,1.000000,0.333000
7,2.000000,1.000000,0.333000,1.000000,1.000000,1.000000,0.333000,3.000000,0.333000,0.500000
8,0.500000,0.333000,0.333000,0.500000,3.000000,0.500000,0.333000,0.500000,0.333000,0.333000
9,3.000000,0.500000,0.500000,3.000000,0.333000,0.333000,1.000000,0.333000,0.333000,0.333000
10,3.000000,0.333000,0.333000,0.500000,0.500000,2.000000,0.500000,2.000000,1.000000,0.333000
11,0.333000,0.500000,1.000000,3.000000,0.333000,1.000000,1.000000,0.500000,0.500000,0.500000
12,1.000000,0.500000,1.000000,2.000000,0.333000,5.000000,0.500000,1.000000,1.000000,0.333000
13,0.500000,3.000000,2.000000,0.500000,1.000000,0.500000,0.333000,0.333000,0.500000,1.000000
14,0.500000,2.000000,2.000000,3.000000,3.000000,0.500000,0.333000,0.333000,1.000000,0.333000
15,2.000000,3.000000,0.500000,0.333000,2.000000,3.000000,0.333000,2.000000,1.000000,0.500000
16,0.333000,3.000000,3.000000,1.000000,0.333000,0.333000,1.000000,0.500000,0.333000,0.333000
17,1.000000,0.500000,3.000000,0.500000,2.000000,1.000000,2.000000,2.000000,0.500000,0.333000
18,0.500000,3.000000,0.333000,1.000000,0.333000,2.000000,3.000000,0.500000,3.000000,0.500000
19,2.000000,0.333000,1.000000,0.333000,0.333000,0.500000,0.500000,0.333000,2.000000,0.333000
20,0.333000,0.333000,0.333000,0.333000,5.000000,0.333000,5.000000,0.333000,0.333000,0.500000
21,3.000000,3.000000,3.000000,3.000000,0.333000,3.000000,0.333000,3.000000,0.333000,0.333000
22,0.500000,0.500000,0.333000,1.000000,2.000000,2.000000,1.000000,1.000000,2.000000,2.000000
23,1.000000,1.000000,1.000000,0.500000,2.000000,2.000000,1.000000,0.500000,2.000000,2.000000
24,0.333000,5.000000,5.000000,0.333000,3.000000,3.000000,0.333000,3.000000,0.333000,0.333000
25,3.000000,3.000000,3.000000,0.333000,3.000000,3.000000,0.333000,0.333000,0.333000,0.333000
26,0.973505,0.916439,1.019567,0.738878,1.026172,1.259611,0.722334,0.822025,0.665422,0.451875
27,0.973505,0.916439,1.019567,0.738878,1.026172,1.259611,0.722334,0.822025,0.665422,0.451875

In [29]:
geo_mean_sum = sum(geo_mean_list)
geo_mean_sum

8.59582812949538

In [30]:
# 데이터프레임의 컬럼수 파악
colums_cnt = len(survey.columns)
colums_cnt

10

In [32]:
# 각 컬럼의 가중치를 계산하여 리스트에 저장
weights_list = []
for i in range(colums_cnt):
    weights_list.append(geo_mean_list[i]/geo_mean_sum)

In [33]:
# 기하평균 출력
print('가중치 (Weights)\n')
for i,j in zip(survey, weights_list):
    #print('{} : {}'.format(i, j))
    print('{} : {}'.format(i, round(j,3)))  # 소수점 3 자리수

가중치 (Weights)

문항 1 : 0.113
문항 2 : 0.107
문항 3  : 0.119
문항 4 : 0.086
문항 5 : 0.119
문항 6 : 0.147
문항 7  : 0.084
문항 8  : 0.096
문항 9  : 0.077
문항 10 : 0.053

In [34]:
# 가중치 합 확인
su_ = sum(list(weights_list))
print(su_)

1.0000000000000002

In [35]:
# 데이터프레임에 가중치 값 추가
survey = survey.append(pd.Series(weights_list, index=survey.columns),ignore_index=True)
survey

<ipython-input-35-474bb4ca3ca4>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  survey = survey.append(pd.Series(weights_list, index=survey.columns),ignore_index=True)

,문항 1,문항 2,문항 3,문항 4,문항 5,문항 6,문항 7,문항 8,문항 9,문항 10
0,0.500000,0.333000,2.000000,1.000000,0.333000,1.000000,0.500000,0.333000,0.500000,0.333000
1,3.000000,0.333000,3.000000,0.500000,2.000000,1.000000,0.500000,0.333000,1.000000,0.500000
2,2.000000,0.500000,0.333000,0.333000,2.000000,2.000000,0.500000,1.000000,0.333000,0.500000
3,0.333000,0.333000,0.500000,2.000000,3.000000,0.500000,1.000000,0.500000,0.333000,0.500000
4,2.000000,0.500000,2.000000,0.500000,0.500000,3.000000,0.333000,3.000000,0.500000,0.333000
5,1.000000,2.000000,3.000000,0.333000,0.333000,3.000000,3.000000,2.000000,2.000000,0.333000
6,1.000000,2.000000,0.500000,0.333000,2.000000,3.000000,3.000000,2.000000,1.000000,0.333000
7,2.000000,1.000000,0.333000,1.000000,1.000000,1.000000,0.333000,3.000000,0.333000,0.500000
8,0.500000,0.333000,0.333000,0.500000,3.000000,0.500000,0.333000,0.500000,0.333000,0.333000
9,3.000000,0.500000,0.500000,3.000000,0.333000,0.333000,1.000000,0.333000,0.333000,0.333000
10,3.000000,0.333000,0.333000,0.500000,0.500000,2.000000,0.500000,2.000000,1.000000,0.333000
11,0.333000,0.500000,1.000000,3.000000,0.333000,1.000000,1.000000,0.500000,0.500000,0.500000
12,1.000000,0.500000,1.000000,2.000000,0.333000,5.000000,0.500000,1.000000,1.000000,0.333000
13,0.500000,3.000000,2.000000,0.500000,1.000000,0.500000,0.333000,0.333000,0.500000,1.000000
14,0.500000,2.000000,2.000000,3.000000,3.000000,0.500000,0.333000,0.333000,1.000000,0.333000
15,2.000000,3.000000,0.500000,0.333000,2.000000,3.000000,0.333000,2.000000,1.000000,0.500000
16,0.333000,3.000000,3.000000,1.000000,0.333000,0.333000,1.000000,0.500000,0.333000,0.333000
17,1.000000,0.500000,3.000000,0.500000,2.000000,1.000000,2.000000,2.000000,0.500000,0.333000
18,0.500000,3.000000,0.333000,1.000000,0.333000,2.000000,3.000000,0.500000,3.000000,0.500000
19,2.000000,0.333000,1.000000,0.333000,0.333000,0.500000,0.500000,0.333000,2.000000,0.333000
20,0.333000,0.333000,0.333000,0.333000,5.000000,0.333000,5.000000,0.333000,0.333000,0.500000
21,3.000000,3.000000,3.000000,3.000000,0.333000,3.000000,0.333000,3.000000,0.333000,0.333000
22,0.500000,0.500000,0.333000,1.000000,2.000000,2.000000,1.000000,1.000000,2.000000,2.000000
23,1.000000,1.000000,1.000000,0.500000,2.000000,2.000000,1.000000,0.500000,2.000000,2.000000
24,0.333000,5.000000,5.000000,0.333000,3.000000,3.000000,0.333000,3.000000,0.333000,0.333000
25,3.000000,3.000000,3.000000,0.333000,3.000000,3.000000,0.333000,0.333000,0.333000,0.333000
26,0.973505,0.916439,1.019567,0.738878,1.026172,1.259611,0.722334,0.822025,0.665422,0.451875
27,0.973505,0.916439,1.019567,0.738878,1.026172,1.259611,0.722334,0.822025,0.665422,0.451875
28,0.113253,0.106614,0.118612,0.085958,0.119380,0.146538,0.084033,0.095631,0.077412,0.052569

In [22]:
# "큐레이션 측면에서 초코케이크는 비빔국수보다 얼마만큼 우월합니까?"라는 질문 응답에 대한 기하평균을 계산합니다.
a = gmean(survey['문항 1'])
b = gmean(survey['문항 2'])
c = gmean(survey['문항 3'])
d = gmean(survey['문항 4'])
e = gmean(survey['문항 5'])
f = gmean(survey['문항 6'])
g = gmean(survey['문항 7'])
h = gmean(survey['문항 8'])
i = gmean(survey['문항 9'])
j = gmean(survey['문항 10'])

KeyError: ignored

In [ ]:
# 기하평균을 대표값으로 쌍대 비교 행렬을 구하고 np01라고 부르기로 합니다.
np01 = np.array([[1, a, b], [1/a, 1, c], [1/b, 1/c, 1]])
# np01이 어떻게 생겼는지 확인합니다.
print(np01)